name = "logger-service"
main = "src/index.js"
compatibility_date = "2024-09-25"

# Development environment (default)
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
SERVICE_NAME = "logger-service"
MAX_LOG_SIZE = "10485760"  # 10MB
RATE_LIMIT_PER_MINUTE = "1000"
RETENTION_DAYS = "30"

# KV namespace for log storage
[[kv_namespaces]]
binding = "LOGS_KV"
id = "logs-kv-dev"
preview_id = "logs-kv-dev-preview"

# D1 database for complex queries and analytics
[[d1_databases]]
binding = "LOGS_DB"
database_name = "logs-db-dev"
database_id = "logs-db-dev-id"

# Staging environment
[env.staging]
name = "logger-service-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "info"
SERVICE_NAME = "logger-service-staging"
MAX_LOG_SIZE = "10485760"
RATE_LIMIT_PER_MINUTE = "5000"
RETENTION_DAYS = "90"

[[env.staging.kv_namespaces]]
binding = "LOGS_KV"
id = "logs-kv-staging"

[[env.staging.d1_databases]]
binding = "LOGS_DB"
database_name = "logs-db-staging"
database_id = "logs-db-staging-id"

# Production environment
[env.production]
name = "logger-service-production"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
SERVICE_NAME = "logger-service-production"
MAX_LOG_SIZE = "10485760"
RATE_LIMIT_PER_MINUTE = "10000"
RETENTION_DAYS = "365"

[[env.production.kv_namespaces]]
binding = "LOGS_KV"
id = "logs-kv-production"

[[env.production.d1_databases]]
binding = "LOGS_DB"
database_name = "logs-db-production"
database_id = "logs-db-production-id"