name = "logger-service"
main = "src/index.js"
compatibility_date = "2024-09-25"

# Development environment (default)
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
SERVICE_NAME = "logger-service"
MAX_LOG_SIZE = "10485760"  # 10MB
RATE_LIMIT_PER_MINUTE = "1000"
RETENTION_DAYS = "30"

# KV namespace for log storage (fast access, temporary storage)
[[kv_namespaces]]
binding = "LOGS_KV"
id = "REPLACE_WITH_ACTUAL_KV_ID"
preview_id = "REPLACE_WITH_ACTUAL_PREVIEW_ID"

# NOTE: Using existing data-access service instead of D1
# Complex queries and persistent storage will be handled via DATA_SERVICE_URL

# Staging environment
[env.staging]
name = "logger-service-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "info"
SERVICE_NAME = "logger-service-staging"
MAX_LOG_SIZE = "10485760"
RATE_LIMIT_PER_MINUTE = "5000"
RETENTION_DAYS = "90"

[[env.staging.kv_namespaces]]
binding = "LOGS_KV"
id = "REPLACE_WITH_ACTUAL_STAGING_KV_ID"
preview_id = "REPLACE_WITH_ACTUAL_STAGING_PREVIEW_ID"

# Production environment
[env.production]
name = "logger-service-production"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
SERVICE_NAME = "logger-service-production"
MAX_LOG_SIZE = "10485760"
RATE_LIMIT_PER_MINUTE = "10000"
RETENTION_DAYS = "365"

[[env.production.kv_namespaces]]
binding = "LOGS_KV"
id = "REPLACE_WITH_ACTUAL_PRODUCTION_KV_ID"
preview_id = "REPLACE_WITH_ACTUAL_PRODUCTION_PREVIEW_ID"